// <auto-generated />
namespace sw_EnligateWeb.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class update_Records : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(update_Records));
        
        string IMigrationMetadata.Id
        {
            get { return "201612141623389_update_Records"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
