// <auto-generated />
namespace sw_EnligateWeb.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class addcreated_atuser : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addcreated_atuser));
        
        string IMigrationMetadata.Id
        {
            get { return "201705301641236_add created_at user"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
