// <auto-generated />
namespace sw_EnligateWeb.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class reportloginHistory : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(reportloginHistory));
        
        string IMigrationMetadata.Id
        {
            get { return "201703172347158_report-login-History"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
