// <auto-generated />
namespace sw_EnligateWeb.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class reportRebuild : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(reportRebuild));
        
        string IMigrationMetadata.Id
        {
            get { return "201703180016062_report-Rebuild"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
